### ISSUE TITLE
Homebrew App Store

### ISSUE THREAD

**Issue by tsndr** [lud99/botw-unexplored#12]
Can you please put it on the **Homebrew App Store**? Makes it so much easier to install and keep up to date.

**Comment by lud99** [comment]
Hi, I’m not too familiar with the homebrew App Store, so do you mind explaining how I should go about doing so?

**Comment by tsndr** [comment]
[Homebrew App Store](https://github.com/fortheusers/hb-appstore/releases/latest) is a marketplace for Switch Homebrew Apps (and other consoles). I personally use it exclusively for downloading homebrew since it makes it super easy for me to keep my homebrew apps up to date. It is also part of the **Recommended Defaults** preset of [SD Setup](https://www.sdsetup.com/console?switch), which many people use to get started with homebrew on the Switch.

I've never published a Switch App myself but it seems like you just have to fill out [this form](https://submit.fortheusers.org/) and you should be good.

**Comment by tsndr** [comment]
Are you planning to submit it?

**Comment by lud99** [comment]
I'm so sorry, I totally forgot about submiting it. I have done it now, so it'll probably be up in a few days.

**Comment by lud99** [comment]
It’s available now!
