### ISSUE TITLE
Support for TotK

### ISSUE THREAD

**Issue by TeleTubby666** [lud99/botw-unexplored#18]
Hi,

it’s obvious that someone would ask for that. And that someone is me :)

So I would like to request support for Tears of the Kingdom which also supports up to 300 stamps. It would help a lot.

Thanks in advance!

**Comment by lud99** [comment]
Hi! 
Thank you for your interest in my app and for writing your request. Sadly, I cannot promise that I will do anything as I'm not sure I have the time to spare to work on it right now (I have to play the game myself first ofc :) ). But i agree that it would be a great thing to have!

Also, there are some technical issues that would have to to overcome if it is to work for Tears of the Kingdom aswell. The savefile reading would have to be rewritten and the korok guides that are taken from Zelda Dungeon's website wouldn't work as they don't exist for Totk yet, along other stuff as well probably. But it is certainly possible.
Some smart people have already figured out the reading of the savefile, such as this execelent fella (https://github.com/marcrobledo/savegame-editors/tree/master/zelda-totk), so it may not be too troublesome to implement.

I may come back and add support later once I have played through the game more, but in the in the meantime anyone else is more than welcome to update my app and work on it themselves!

**Comment by Tiger3x** [comment]
> Oi! Obrigado por seu interesse em meu aplicativo e por escrever sua solicitação. Infelizmente, não posso prometer que farei nada, pois não tenho certeza se tenho tempo de sobra para trabalhar nisso agora (tenho que jogar o jogo sozinho primeiro :)). Mas concordo que seria ótimo ter!
> 
> Além disso, existem alguns problemas técnicos que precisam ser superados para que funcione para Tears of the Kingdom também. A leitura do savefile teria que ser reescrita e os guias korok que são retirados do site de Zelda Dungeon não funcionariam porque ainda não existem para Totk, junto com outras coisas provavelmente. Mas certamente é possível. Algumas pessoas espertas já descobriram a leitura do savefile, como este excelente cara ( https://github.com/marcrobledo/savegame-editors/tree/master/zelda-totk ), então pode não ser muito problemático para implemento.
> 
> Posso voltar e adicionar suporte mais tarde, depois de jogar mais o jogo, mas enquanto isso, qualquer outra pessoa é mais do que bem-vinda para atualizar meu aplicativo e trabalhar nele!

Hello, recently the zelda dungeon updated and is compatible with totk lol it would be great for you to make this version for totk lol

**Comment by lud99** [comment]
Hi!

I can now say that a version for Tears of the Kingdom is close to being finished. I have been busy with other stuff so development has moved at a snails pace and I apologize for that. But... I hope to be able to release it during this week!

**Comment by lud99** [comment]
It finally happend.... I finished it! Thank you for your patiance and I hope it was worth the wait :)
https://github.com/lud99/totk-unexplored

**Comment by TeleTubby666** [comment]
Whoop whoop! Thank you very much!

**Comment by JonJaded** [comment]
Actual GOAT status, thank you.
