### ISSUE TITLE
Add "Korok Paths"

### ISSUE THREAD

**Issue by d4mation** [lud99/botw-unexplored#2]
Some Koroks require you to follow a path in order to find them--For some, you have to follow a path of flowers. For others, you step on a stump and then you have to quickly run through a ring of light to get the Korok.

In both cases, the Korok's in-game location is at the end of that path. In some cases, the starting location is relatively far away from the ending location which can make finding these a bit challenging. Having something to tell the user where to start for these Koroks would be very helpful.

In my web app for this, I determined the different points on the path that you have to visit to get these Koroks and visually represented them as a line:

![image](https://user-images.githubusercontent.com/7770631/110640399-c8d1ff00-817e-11eb-98be-3c76dc0196af.png)

Some other maps do similar things as well: https://www.zeldadungeon.net/breath-of-the-wild-interactive-map/

I made modifications here to find that data: https://github.com/d4mation/botw-tools/blob/include-reference-data/map.py

And then here to translate that data into a useable format: https://github.com/d4mation/botw-waypoint-map/blob/gh-pages/map.py

Here's some notes I made regarding which entities to look for in the datamined information: https://github.com/d4mation/botw-unexplored-viewer/issues/2#issuecomment-525770631

Ultimately, I just made a separate variable to store the Paths and then associated them with the "Internal Name" for each Korok: https://github.com/d4mation/botw-unexplored-viewer/blob/876dcb341c6b11a7d00c864ecc4a90a15ce7c9fc/assets/js/map-locations.js#L1

https://mrcheeze.github.io/botw-object-map/ is really useful when trying to figure out what certain entity names actually are by showing them directly on the map.

**Comment by lud99** [comment]
Added! Thanks for all the links!
