### ISSUE TITLE
App closes immediately

### ISSUE THREAD

**Issue by aerialdigest** [lud99/botw-unexplored#8]
Hello, when I launch the app it goes to a black screen for a moment and then closed back to homebrew launcher. I'm using SXOS 3.1.0 and FW 10.2.0

**Comment by lud99** [comment]
Hi, is BotW running when you try to launch the app?

**Comment by aerialdigest** [comment]
No. I've tried it with it running and without it running, but it behaves the same regardless.

**Comment by lud99** [comment]
I'm sorry but I think there's very little I can do to try and debug the issue. I don't have sx os so I sadly don't have a clue what's going wrong. Let's hope that the next update somehow fixes the issue.  I could probably add some sort of logging to maybe get some more details. I could send a nsp with logging capabilities here later that you could try.

**Comment by aerialdigest** [comment]
Okay, that sounds like a good plan. I appreciate the help.

**Comment by lud99** [comment]
Just a quick question, are you prompted to choose a profile, or does it crash before that?

**Comment by aerialdigest** [comment]
It crashes before that. I use the SXOS homebrew launcher, and it will be a black screen for maybe half a second, then it boots me back. When I'm booted back, the launcher says "Scanning..." in the bottom right corner for a half second. Hope that helps.

**Comment by lud99** [comment]
Hey, so I've created a version that you can try out now. Please send me the text file that is saved to the sd card at ```switch/botw-unexplored/log.txt``` (it has all the logs). This version has a lot more features than the one you'd normally download and is not 100% finished, just so you know. I had to make the nro into a zip file, so extract it in your ```switch``` folder like you'd normally do.

Download link:
[botw-unexplored.zip](https://github.com/lud99/botw-unexplored/files/6214631/botw-unexplored.zip)

**Comment by aerialdigest** [comment]
Okay, this version allowed me into the map, but then it says that there's "no save data for this user". It asks me to choose a profile, but when I try that option, nothing happens. Here's the log file. 
[log.txt](https://github.com/lud99/botw-unexplored/files/6214986/log.txt)

**Comment by lud99** [comment]
After looking at the log, it seems that it fails to open the profile picker. It could be that sxos simply doesn’t support the profile picker or accounts in general. If that’s the case then I’m afraid you would have to use atmosphere.

One last thing you could try is to launch some game with the profile that has your BotW save (any game except botw). Try to launch the app again and see if there’s anything different

**Comment by aerialdigest** [comment]
Launching it with a different game open worked! I now can use the app. Awesome additions to the functionality, btw. Very useful.

**Comment by aerialdigest** [comment]
Further update, after opening the app the first time using a different game open, the profile picker works. I don't have to have a different game open. After the first connection the app seems to know to open my account. Thanks again for troubleshooting for me.

**Comment by lud99** [comment]
Glad you find it useful and it’s great to hear that it finally works! Now I can sleep peacefully at night :)
